### PR TITLE
Changed finding HOME. Fix for issue #145

### PR DESCRIPTION
**Pull request by lechat**

### CODE REVIEW

**Comment by asmeurer** [comment]
I think it would be better to only look for $HOME and if it isn't there, or can't be written to, to completely skip trying to use a config file.

**Comment by asmeurer** [comment]
It's also worth noting that this breaks backwards compabitility.

**Comment by lechat** [comment]
@asmeurer could you elaborate about backwards compatibility? w/o that change pudb just breaks if $HOME is not set.

**Comment by asmeurer** [comment]
The backwards compatibility is broken for the fallback to `/`.

**Comment by lechat** [comment]
I think that it is wrong to fallback to ``/``, no matter what: this is not a place for user apps to write to. This dir rarely have permission for non-elevated user to write.

**Comment by inducer** [comment]
I agree with @asmeurer that a config file should only be looked for in $HOME.

**Comment by inducer** [comment]
Is falling back to the current directory really a good idea, though?

**Comment by asmeurer** [comment]
I don't really see how any of the fallbacks (`/`, `TEMP`, or `.`) are good ideas.

**Comment by inducer** [comment]
Yeah, probably not.

**Comment by lechat** [comment]
Ok. Since that is not a good idea, I am closing this pull requests and submitting another one.

**Pull request closed without merging**
