### PR TITLE
Added a base tests for settings

### PR DESCRIPTION
**Pull request by discort**
#242 
Execute `pip install -r requirements.dev.txt`

To run tests with a coverage:
`py.test --cov=pudb tests`

Tested with python3.5 and 2.7

### CODE REVIEW

**Comment by asmeurer** [comment]
I didn't even realize that we already had some tests. We should enable Travis or Circle (I have no preference), so that we can at least see that they are working.

**Comment by inducer** [comment]
FWIW, I already have CI running on my internal gitlab: https://gitlab.tiker.net/inducer/pudb

**Comment by inducer** [comment]
(But I'm not against switching to Travis/Circle.) Config is in `.gitlab-ci.yml`.

**Comment by discort** [comment]
What about to add the information to a docs
1. How to setup a development environment
2. How to run tests locally

**Comment by inducer** [comment]
Added both of you to the Gitlab project. You should have received email--check your spam folders.

**Comment by inducer** [comment]
@discort It'd be fantastic if you could move this pull request there to have the CI run on it.

**Comment by discort** [comment]
I have no idea how to use GitLab. I pushed my branch there but I suppose I did it wrong

**Comment by inducer** [comment]
You're totally fine. Created a merge request for you: https://gitlab.tiker.net/inducer/pudb/merge_requests/1

**Comment by asmeurer** [comment]
Is it possible to have GitLab run the tests on pull requests automatically, and update the GitHub status?

**Comment by asmeurer** [comment]
I see, so it's already running flake8, with those given things ignored. So you just need to add ignore flags for the unused imports in the compat file.

**Comment by asmeurer** [comment]
Also, flake8 ought to be run in each Python build, not as a separate build. That way, it can catch Python 2/3 incompatibilities (e.g., if you use `unicode` in Python 2 without importing it from compat, flake8 will fail if run in Python 3 but not in Python 2).

**Comment by inducer** [comment]
> Also, flake8 ought to be run in each Python build, not as a separate build.

It'll stay a  separate build, but if you'd like to run it for 2 and 3, feel free to hack this: https://gitlab.tiker.net/inducer/ci-support/

**Pull request merged**
