### PR TITLE
Add nord-256 theme

### LINKED ISSUE #567: Nord Theme
**Is your feature request related to a problem? Please describe.**

I'd like to have a pudb theme similar to this one: 

https://github.com/arcticicestudio/nord-vim
https://www.nordtheme.com/ports/tmux
https://www.nordtheme.com/

**Describe the solution you'd like**

I'd like to have a nord theme.

### PR DESCRIPTION
**Pull request by jgarte**
Closes #567 

image

### CODE REVIEW

**Comment by inducer** [comment]
To cut down on noise in my email, I'm unsubscribing from this PR. I've also converted it to formal draft status. When it next needs my attention, please @-mention me or hit the "request review" button. Otherwise, I may not see your messages in a timely manner.

**Review by mvanderkamp — COMMENTED** [review]
Generally I think this looks great! I'm not overly familiar with the nord theme and normally use a light theme but this is very easy on the eyes. You've done a great job structuring the theme and code! And an admirable job mapping the palette to the 256 xterm colors.

A few notes. Since I'm generally unfamiliar with the nord theme, feel free to dismiss any of these.
- nord8 and nord9 are very similar, so e.g. for the `"highlighted_var_label"` the label just appears as one solid block of colour for me. Same for the "return" label.
- It's a bit hard to read nord0 over nord1 (`"sidebar three"`) or over nord2 (`"focused sidebar two"`)
- Comments are also a bit dark. Would a colour in the 244/245 range be reasonable, or nord10?
- The section header in the menus is hard to read (`"group head"`). Personally I favour just changing the background colour for that style to match the `"background"`.
- The screenshots [here](https://www.nordtheme.com/ports/vim) suggests a few syntax changes:
    1. Strings have a greenish highlight. Perhaps something around `h150`?
    2. Numbers have a red highlight, but it's softer than nord11. Something like `h138` maybe?
    3. Operators have the same bluish highlight as keywords

**Comment by jgarte** [comment]
@mvanderkamp Thanks for the review and suggestions! It is much appreciated! 

Would you like to collaborate on this? 

I can give you push access to my fork branch for this PR. I'm not sure when I'll be able to work on this. It probably won't be for at least a month.

**Comment by mvanderkamp** [comment]
Sure, no guarantees I'll have much time either but I might find a moment.

**Comment by mvanderkamp** [comment]
@jgarte I wasn't able to push to your branch, so I opened a PR at: https://github.com/jgarte/pudb/pull/1

Feel free to revise in whatever way you like.

**Comment by jgarte** [comment]
@inducer Hi, I merged @mvanderkamp updated changes to this PR.

What do you think?

LGTM.

**Pull request closed without merging**
