### PR TITLE
get_executable_lines_for_file: tolerate files that do not compile

### PR DESCRIPTION
**Pull request by jsoref**
Fixes issue #178

### CODE REVIEW

**Comment by inducer** [comment]
Minor wrinkle: You probably want to use the result in `execable_lines` in the `if` statement just below. Looks good otherwise.

**Comment by asmeurer** [comment]
Yep, agree with that.

**Comment by jsoref** [comment]
Oops, yes, I meant to do that.

**Comment by jsoref** [comment]
(Done)

**Comment by inducer** [comment]
Thanks for your contribution!

**Pull request merged**
