### PR TITLE
Reorganize themes and add gray-light-256 and nord-dark-256 themes

### LINKED ISSUE #248: Move themes out to separate files
All current themes are defined inside a `theme.py` module. It looks like the next:
```
elif theme == "midnight":
        # {{{ midnight

        # Based on XCode's midnight theme
        # Looks best in a console with green text against black background
        palette_dict.update({
            "variables": ("white", "default"),

            "var label": ("light blue", "default"),
            "var value": ("white", "default"),
         ...
```
I propose to create a separate folder, for example, `themes`. Each theme will be as a separate file JSON or YAML inside a created folder.

I think the theme is not related to an application. Consider a terminal or popular text editors. All of their themes are separate files which easy to install without changing a code.

### LINKED ISSUE #567: Nord Theme
**Is your feature request related to a problem? Please describe.**

I'd like to have a pudb theme similar to this one: 

https://github.com/arcticicestudio/nord-vim
https://www.nordtheme.com/ports/tmux
https://www.nordtheme.com/

**Describe the solution you'd like**

I'd like to have a nord theme.

### LINKED ISSUE #611: Greyscale Theme
**Is your feature request related to a problem? Please describe.**

I'd like to request a grey scale theme that looks like eink displays. Mono is not grey scale, for example.

**Describe the solution you'd like**

Something like this emacs color theme:

https://github.com/gugod/grey-paper-theme#screenshots

### PR DESCRIPTION
**Pull request by mvanderkamp**
This PR adds two new themes: `gray-light-256` and `nord-dark-256`. I also figured it was time to take a crack at splitting the themes out into their own files.

Oh, and there's a minor fix for an issue that was causing the debugger to crash when it couldn't find a custom theme file on startup.

Let me know what you think!

### gray-light-256 Preview

Light grayscale 256 preview

### nord-dark-256 Preview

Screenshot 2023-09-17 at 14 41 29

---
Closes #611 
Closes #572
Closes #567
Closes #248

### CODE REVIEW

**Comment by mvanderkamp** [comment]
@jgarte Something like this?

**Comment by jgarte** [comment]
> @jgarte Something like this?

Yep, that looks great!

**Comment by mvanderkamp** [comment]
This should probably not be merged before #572, because of the refactor around themes getting their own modules.

**Comment by inducer** [comment]
@mvanderkamp Could you look into the linker failure?

> This should probably not be merged before https://github.com/inducer/pudb/pull/572, because of the refactor around themes getting their own modules.

Could you clarify how the two PRs would interact? Maybe @jgarte can give you permission to simply roll the nord-256 theme into this PR, to keep things simple?

**Comment by jgarte** [comment]
> Could you clarify how the two PRs would interact? Maybe @jgarte can give you permission to simply roll the nord-256 theme into this PR, to keep things simple?

You mean for me to give write access to the nord branch? @inducer

**Comment by mvanderkamp** [comment]
I think it would work quite easily for me to add the nord theme to this PR as just a copy-paste, I would have to do something roughly similar anyway to reconcile the two PRs. I'll take a go at it. @jgarte I'll see if there's some git shenanigans I can do to still make you the author of the theme in the commits.

**Comment by mvanderkamp** [comment]
@jgarte Okay it was actually easy enough to just pull your branch into mine, so git history should still be there as expected.

I'm getting some odd pylint errors:
```
************* Module pudb.debugger
pudb/debugger.py:2479:36: E1101: Module 'urwid.version' has no 'VERSION' member (no-member)
pudb/debugger.py:2807:25: E1133: Non-iterable value keys is used in an iterating context (not-an-iterable)
```

**Comment by mvanderkamp** [comment]
Ah yeah urwid has made some breaking changes for us: https://github.com/urwid/urwid/commit/8d8e4b678cc0f93149a4a964b26ee11fb136ea0f

Not sure why there's a "non-iterable" failure though

**Comment by mvanderkamp** [comment]
I added a restriction to not use the latest releases of urwid, that did the trick for this PR.

**Comment by ThomasJRyan** [comment]
Looking forward to this getting merged in. I've got an idea on how to expand it further now that the themes have been broken out into their own files

**Comment by jgarte** [comment]
I'm also looking forward to seeing this merged :)

**Comment by ThomasJRyan** [comment]
Looks like you'll also be able to close https://github.com/inducer/pudb/issues/248

**Comment by mvanderkamp** [comment]
Oh nice! I've reverted the `urwid` restriction, since the conflict is fixed.

**Comment by inducer** [comment]
At this point, all I can do is squash-merge this PR, but since multiple contributors are involved, that doesn't seem like the right choice. Could you clean up the history and rebase so that I can simply merge-rebase?

**Comment by mvanderkamp** [comment]
Whew that was more effort than I expected! Basically had to redo all the nord theme commits as though they were originally done in their own file. But it looks like it worked, and maintained attribution! :tada:

**Comment by jgarte** [comment]
> Whew that was more effort than I expected! Basically had to redo all the nord theme commits as though they were originally done in their own file. But it looks like it worked, and maintained attribution! 🎉

Thanks for doing that. It is much appreciated!

**Comment by inducer** [comment]
LGTM. Thanks!

**Pull request merged**
