### PR TITLE
Variables can show/hide methods

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
This is in response to #137 (is there a way to combine them?)
Not sure I like it yet: it's still annoying that to see `_private`, I have to also see `__doc__`, `__dict__`, etc.  Maybe I will also make '`*`' be a tri-state?

**Comment by inducer** [comment]
I closed #137 in favor of this. I think I would support '*' being tri-state. I don't use private attributes much, but I think the tri-state semantics are what I'd prefer if I did.

**Comment by nedbat** [comment]
OK, I've made '`*`' cycle public/private/all.  Not quite sure how best to describe it in the help, dialog, etc.  Tweaks welcome of course.

**Comment by inducer** [comment]
How about:

```diff
-    * - cycle public/private/dunder members
-    m - toggle methods
+    * - cycle attribute visibility: public/_private/__dunder__
+    m - toggle method visibility
```

There's one slight usability wrinkle with the multi-state visibility, which is that sometimes hitting `*` has no visible effect. I was wondering if a state indicator of some sort might help that.

**Comment by nedbat** [comment]
I see what you mean about `*` not having a visible effect.  Do you have an idea what the indicator would be?

**Comment by inducer** [comment]
I am currently thinking `[*]`/`[_]`/`[__]` in front of the variable name when it's unfolded, but I don't know how much I'd like that in the end. If you've got a suggestion, shoot.

**Comment by nedbat** [comment]
Another option: riffing on the `<omitted private attributes>` that is shown if there is nothing else to show, we could add a line like that when changing visibility wouldn't show anything more.  So if an object has only public data attributes, typing `*` would add a line: `<no private attributes>`, and typing `m` would add `<no methods>`, etc.

**Comment by inducer** [comment]
That marker could be off the screen, though.

**Comment by nedbat** [comment]
Can you show a specific example of what you mean by "`[*] / [_] / [__]` in front of the variable name" ? I'm not sure how you are envisioning it.   `[pub] / [pri] / [all]` might be more understandable, btw.

**Comment by inducer** [comment]
When in the collapsed case some variable might show up as:
```
var_name: SomeClass
```
in the expanded case, I'm imagining
```
var_name: [pub] SomeClass
| attr1: int
```
or
```
var_name: SomeClass [pub]
| attr1: int
```
Btw: yep, `[pub]` et al are better.

**Comment by nedbat** [comment]
OK, I added a marker when values are expanded.  It has two parts, `pub`/`pri`/`all` for access level, and if methods are shown, it adds `+()`, which might be too cryptic.

**Comment by nedbat** [comment]
BTW, I don't understand the urwid stuff enough to know how to make the marker be drawn differently (grayer) than the rest of the label.

**Comment by inducer** [comment]
Thanks very much for your contribution! I'm a huge fan. I've just released 2015.3 with your changes in it.

**Comment by nedbat** [comment]
Yay! :)

**Pull request merged**
