### PR TITLE
Improve some text width calculations

### PR DESCRIPTION
**Pull request by asmeurer**
Preliminary fix for the issues described at https://github.com/inducer/pudb/issues/271. Still need confirmation that it fixes https://github.com/inducer/pudb/issues/271 (I don't know that it does). And I still need to add a lot of tests. We need to better hammer this code in the tests so that all the double- and zero-width corner cases don't crash pudb.

### CODE REVIEW

**Comment by inducer** [comment]
This looks good to me. If you'd like to merge it now, I say go ahead. Alternatively, if you'd like to wait until there are more tests or confirmation from @cdman, that's fine, too.

**Comment by asmeurer** [comment]
I want to write some tests first.

**Comment by asmeurer** [comment]
I'm also unsure if my changes to var_view are needed. I haven't yet found a bug that actually is fixed by them.

**Comment by inducer** [comment]
As evidenced by #271, I suspect we're better off merging this than not. The tests can always go in later. What do you think? You have my go-ahead to merge this.

**Comment by asmeurer** [comment]
I tested and the changes in var_view aren't what fixed that issue. But I agree we should merge it.

**Pull request merged**
