### PR TITLE
Added TravisCI and codecov.io support

### PR DESCRIPTION
**Pull request by discort**
1. Register at https://travis-ci.org and here https://codecov.io
2. Syncronize `pudb` repo.
3. In the TravisCI setting set environment variable `COVERAGE` with a value from of the upload token from codecov.io (see pudb settings at codecov.io)
4. The badges badges will be added to readme.rst

An example: https://github.com/discort/pudb

### CODE REVIEW

**Comment by inducer** [comment]
Thx!

**Comment by discort** [comment]
@inducer 
Need to add `__init__.py` to a `test` folder

**Comment by inducer** [comment]
FYI: Passes now. Thanks for setting this up.

**Comment by inducer** [comment]
Coverage isn't working. I've added `CODECOV_TOKEN` with the correct value to the Travis env vars, but... nothing.

**Comment by inducer** [comment]
Maybe the upload script is looking in the wrong spot--could you take a look?

**Comment by discort** [comment]
@inducer 
You added `CODECOV_TOKEN` env variable but script uses `COVERAGE` https://github.com/inducer/pudb/blob/master/upload_coverage.sh#L3

These names should be the same

**Comment by inducer** [comment]
Fixed, as of a while ago. Thanks for your help.

**Pull request merged**
