### PR TITLE
Adding some more emacs bindings to the REPL

### PR DESCRIPTION
**Pull request by FoxLisk**

### CODE REVIEW

**Comment by asmeurer** [comment]
The behavior of C-w seems to be wrong if there is trailing space (compared to ipython).

**Comment by asmeurer** [comment]
It would be nice if we could just use readline to get all the bindings in one fell swoop, but this is good enough.

**Comment by FoxLisk** [comment]
Ah, the C-w wasnt really meant to be compatible with anything in particular besides what made sense to me (which is roughly what zsh does). I'll get it more in line with ipython and submit a new patch

**Comment by FoxLisk** [comment]
I believe this emulates ipython's behaviour pretty well now.

**Comment by inducer** [comment]
Thanks for your contribution!

**Comment by FoxLisk** [comment]
My pleasure! Are you going to put a new package up on pypi?

**Comment by inducer** [comment]
Done.

**Pull request merged**
