### PR TITLE
Show length of array types in var view

### PR DESCRIPTION
**Pull request by Allda**
The new code shows length of set, frozenset, list, tuple and dict type
varibles in variable view.

### CODE REVIEW

**Comment by inducer** [comment]
@asmeurer, what do you think? My only thought is that, depending on the stringifier, this information could be somewhat redundant. But I could also see it being helpful. I'm +0.

**Comment by asmeurer** [comment]
I would do it just for the Type (default) stringifier.

**Comment by inducer** [comment]
Agreed. @Allda, could you move that code into that stringifier?

**Comment by Allda** [comment]
@asmeurer @inducer I moved the code to `type_stringifier()` function

**Comment by inducer** [comment]
LGTM. Thanks!

**Pull request merged**
