### PR TITLE
Implement jump command

### PR DESCRIPTION
**Pull request by asmeurer**
~Right now it doesn't stop on the line (like t), which would be ideal. I can't
figure out how to make it do that. pdb's j does it, so it should be possible.~

~It also isn't documented or heavily tested yet.~

This is ready to go.

See issue #129.

### CODE REVIEW

**Comment by asmeurer** [comment]
OK, I figured this one out. Turns out `end()` causes it to run past the current line so instead we need to update the UI manually. 

It seems to work now for me. Test script:

```py
def test(n):
    return n + 1

def main():
    for i in range(10):
        if test(i) == 5:
            import pudb;pudb.set_trace()

main()
```

Run the script and jump to the `if test(i) == 5` line. You can then press `s` to step into `test()` and `i` still equals 4.

**Comment by FGrose** [comment]
@asmeurer Thank you! This is helping me greatly to test state and debug.

**Comment by inducer** [comment]
This still has a linter failure. Could you take a look/

**Comment by asmeurer** [comment]
I've fixed the issue.

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
