### PR TITLE
Map up/down keys to command history prev/next

### LINKED ISSUE #348: Command history with cursor up in internal shell
When inside the internal shell the cursor-up key just selects the lines in history with no (apparent) useful function. 

It would be nice if it could instead access the history (as does ctrl-p/n).

### PR DESCRIPTION
**Pull request by ned2**
Map up/down keys to command history prev/next when command line is focused

Fixes #348

### CODE REVIEW

**Comment by asmeurer** [comment]
It's not obvious, but you can still arrow up through the history items with this by pressing "right" to select the "<clear>" button, then arrowing up.

**Comment by inducer** [comment]
- Fix the help
- Could you see if we can bind shift+up (or some such) to paging through the console scrollback?

**Comment by ned2** [comment]
Oops yes the help, I forgot about that. done.

With the console scrollback paging, @inducer, do you mean navigating forward/back through blocks of history commands of size greater than 1, or something else?

**Comment by inducer** [comment]
> With the console scrollback paging, @inducer, do you mean navigating forward/back through blocks of history commands of size greater than 1, or something else?

Just navigating *somehow*. Since this takes away cursor up/down as a canonical way to do scrollback navigation, I'd like for something somewhat easy to remember to be put in place. And @asmeurer's go-right-then-up thing is cute, but doesn't count: it's not convenient, obvious, or easy-to-remember.

**Comment by sisrfeng** [comment]
any update?

> Agree, this is super annoying. It's really messing up my muscle memory.
I Agree!

**Comment by asmeurer** [comment]
I think if these two things are addressed this is fine https://github.com/inducer/pudb/pull/392#issuecomment-650694840. I would suggest making a new PR for this, since no work has happened on this one in a while.

**Comment by inducer** [comment]
This was done in #600.

**Pull request closed without merging**
