### PR TITLE
Fixed issue with closing the session in remote debugging

### PR DESCRIPTION
**Pull request by mlubimow**
Fix for https://github.com/inducer/pudb/issues/289.

### CODE REVIEW

**Comment by inducer** [comment]
LGTM! Thanks for your contribution.

**Comment by mlubimow** [comment]
@inducer Actually I realised recently that it's current behaviour also is not fully correct. I was focused on fixing the existing code more than the logic itself, and later I had second thoughts that on continue we probably don't want to close the session, because when in normal remote mode (reverse=False) it might be inconvenient to be required to telnet again. Do you know if there is any hook that would allow us to run some code once the debugged process ends?

On the good side, with reverse=True its easy as its enough to add -k flag to nc (stty -echo -icanon && nc -l -p 6899 -k) to make continue to work as expected.

**Comment by inducer** [comment]
> Do you know if there is any hook that would allow us to run some code once the debugged process ends?

Possibly `atexit`?

**Comment by inducer** [comment]
> Actually I realised recently that it's current behaviour also is not fully correct.

Should we revert this in the meantime?

**Comment by mlubimow** [comment]
@inducer Yeah atexit seems to be a way better idea, I will create another PR fixing this.

**Pull request merged**
